# Generated by Django 3.2.13 on 2022-05-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
